---
title: "Learner Personas"
bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Like you, a *Learner Persona* [@wilson2019]) consists of:

-   a general background, 
-   what you already know, 
-   what you want to know, and 
-   other special needs you may have. 

If you are working on your doctoral thesis, do you identify better with [Celine](#celine) or with [Víctor](#victor)? If you are part of the teaching staff, do your learning needs fit better with those of [Juan](#juan) or with those of [Ana](#ana)?


## Celine {#celine}

Celine has a degree in psychology from England and has just enrolled in the UJI doctoral school. Her doctoral thesis deals with the application of new technologies to improve behavioral therapies for patients diagnosed with gambling addiction.

Celine plans to carry out several experiments with patients during her doctoral period. She knows some tools for data analysis (such as SPSS) from her bachelor's degree, but she has never taken a formal programming course, although she has thought about it often. She sometimes thinks that she suffers from the [impostor syndrome](https://en.wikipedia.org/wiki/Impostor_syndrome) as soon as she faces with programming languages or advanced data analytical tools.

Celine would like to systematize the data analysis of the experiments that she will be conducting in her doctoral project. Yet, above all, she wants to prove to herself that she can learn computational competences. The terms reproducibility and replicability sound familiar to her and she thinks that they can be useful to speed up the tedious work of her experiments, but she does not know where to start.


## Víctor {#victor}

Víctor studied a chemistry degree at UJI and is in the final phase of his PhD thesis on computational chemistry, which he hopes to defend once he completes a planned research stay in France.

Víctor learned R early in his thesis period and it is still the programming language in his research. Like in many other tools, he was self-taught in the use of Github and uses it to version his own software and to collaborate with other colleagues. He has published some relevant articles in which the developed software has been a main contribution.

Víctor wants to improve his skills and expand his knowledge about reproducibible workflows. The best academic journals in his field now require that every submission come with code and data, and he knows that an article published in those high-profile journals can open the door to a postdoc.

## Juan {#juan}

Juan is a professor of Economics at the UJI. He has four six-year research periods and a good record of scientific publications. He is responsible for a quantitative economics course which in turn is the focus of his research.

Juan is surprised by the current hype about the *reproducibility crisis* that he reads about in Science and Nature editorials. He considers that crisis an exaggeration, like so many other buzzwords that he has witnessed in his long academic career. He has never needed reproducibility to have a successful academic career.

Despite this, Juan wants to make sure that his beliefs about reproducibility and reproducible practices are well founded.

## Ana {#ana}

Ana is a professor of Computer Science at the UJI. She hardly never investigates, but she is very active and is concerned with improving her teaching practices. She is responsible for an introductory programming course for large groups of freshmen.

Ana is up to date with teaching innovations and everything related to educational technology. For a decade, she has been applying the most recent learning methodologies and innovative techniques in her classes with considerable success, according to what her students say in surveys.

Ana wants to know if reproducibility and teaching combine in some way, since reproducibility and research always go hand in hand in everything she has read. She is wodering how to bring reproduciblity aspects into her practical sessions, such as in peer asessment and peer instructions, and even for the creation of teaching materials. She is interested in guides and practical examples to get inspired to improving her teaching materials and practical classes.
