---
title: "Act III &#183; Recommendations and practices: GIScience"
description: |
  Scene 1 &#183; AGILE Guidelines
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Learning outcomes...

-   [RRP05] **Organise** a research project to facilitate reproducibility, openness and reuse.

-   [RRP06] **Contrast** the main families of licences for software and data.


## Content...

-   We discuss practices and recommendations to get started with reproducibility


## Organisation & materials

**[Estimated time: 4 hours]**


1.  Who are we? A [brief historical account](https://docs.google.com/presentation/d/14zJk4Rx0JIFIEbF6qy_V1Pi17z0zafbrh9sZxotK0RQ/edit?usp=sharing) of [reproducibility](glossary.html#reproducibility) in the [AGILE conference series](https://agile-online.org/). Check out [Reproducible Research @ AGILE](https://reproducible-agile.github.io/)


2. [Reproducible Publications at AGILE Conferences – Guidelines for Authors, Scientific Reviewers, and Reproducibility Reviewers](https://doi.org/10.17605/OSF.IO/CB7Z8) (December 2020)


[Reproducible Publications at AGILE Conferences – Spanish translation](https://doi.org/10.17605/OSF.IO/MF9BE) (July 2019)

The main OSF project with all documentation about the Reproducible Publications at AGILE Conferences and creation of the guidelines: https://osf.io/phmce/

3. TODO: Evolution Repro Reviews in AGILE (2020-2023)... 

4. TODO: Quantitative vs qualitative research in GIScience




    

