---
title: "Course schedule"
bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This is the current course schedule. Things might change, so check regularly for updates.

## Act I: Setting the stage

We cover learning outcomes [RRP01 to RRP04](index.html#learning-outcomes). We look at landmark examples that have influenced the emphasis on reproducibility in the past decades and explain why reproducibility is so important in current scientific endeavour. We highlight which components may be reproducible and take a PhD perspective for reproducibility too. Next, we start with the **Reproduction Plan** by assessing the reproducibility criteria over research papers.

-   Scene 1: [Reproducibility and replicability](scene11.html)

-   Scene 2: [PhD meets open science](scene12.html)

-   Scene 3: [Pre-reproducibility assessment](scene13.html)

## Act II: Recommendations and practices

We cover learning outcomes [RRP05 to RRP07](index.html#learning-outcomes). We comment and discuss recommendations and suggestions for getting started with reproducibility research practices and applying them to the **Reproduction Plan** to address the weakest aspects identified in Act I. Recommendations below are grouped according to when they are most likely to take them into consideration: before, during and after data analysis. 

-   Scene 1: [Before: basics to get started](scene21.html)

-   Scene 2: [During analysis: coding practices and tools](scene22.html)

-   Scene 3: [After analysis: writing and sharing reproducible resources](scene23.html)


## Act III: Recommendations and practices: GIScience

Same as Act II but focus on the GIScience discipline.

-   Scene 1: [AGILE Guidelines for reproducible papers](scene31.html)


## Act IV: Literate programming & notebooks (separate github repo - obgoing)

We cover learning outcomes [RRP08 to RRP09](index.html#learning-outcomes).

-   Scene 1: [Literate programming y markdown](scene41.html)

-   Scene 2: [Quarto: an open-source scientific and technical publishing system](scene42.html)

-   Scene 3: [Tools and resources](scene43.html)

RRP Learning Outcome 10 - **Reproduction Plan** - is a skill that will be developed throughout the course. Participants will submit their Reproduction Plan to make their next research project/work or technical writing more reproducible.